version: '3'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpass
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: prestamos_db
    ports:
      - "5432:5432"
    networks:
      - mynetwork
    volumes:
      - pg_data:/var/lib/postgresql/data

  orquestador:
    build: ./microservicio-biblioteca
    container_name: biblioteca_orquestador
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/biblioteca_db
      - SPRING_DATASOURCE_USERNAME=mysqluser
      - SPRING_DATASOURCE_PASSWORD=mysqlpass
    ports:
      - "8082:8082"
    networks:
      - mynetwork
    depends_on:
      - mysql

  inventario:
    build: ./microservicio-inventario
    container_name: inventario_service
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/inventario_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: user_password
    networks:
      - mynetwork
    depends_on:
      - mysql

  prestamo-service:
    build: ./Prestamo
    container_name: prestamo_service
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/prestamos_db
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    depends_on:
      - postgres

networks:
  mynetwork:
    driver: bridge

volumes:
  mysql_data:
  pg_data:
